const ErrorCodes = {
  // 인증 관련
  UNAUTHORIZED: 'AUTH_001',
  INVALID_TOKEN: 'AUTH_002',
  TOKEN_EXPIRED: 'AUTH_003',
  INVALID_CREDENTIALS: 'AUTH_004',
  
  // 권한 관련
  FORBIDDEN: 'PERM_001',
  INSUFFICIENT_PERMISSIONS: 'PERM_002',
  
  // 데이터 관련
  VALIDATION_ERROR: 'DATA_001',
  RESOURCE_NOT_FOUND: 'DATA_002',
  DUPLICATE_RESOURCE: 'DATA_003',
  
  // 파일 업로드 관련
  FILE_TOO_LARGE: 'FILE_001',
  INVALID_FILE_TYPE: 'FILE_002',
  UPLOAD_FAILED: 'FILE_003',
  
  // 서버 관련
  INTERNAL_SERVER_ERROR: 'SERVER_001',
  SERVICE_UNAVAILABLE: 'SERVER_002',
  RATE_LIMIT_EXCEEDED: 'SERVER_003',
};

module.exports = ErrorCodes;